---
title: "중간고사 B형"
author: "양승훈"
date: '2017 10 24 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 소개

한 학기의 반이 지났습니다. 수업 열심히 따라오느라 고생이 많았습니다.
중간고사는 여러분이 수업을 얼마나 충실히 따라왔는지를 확인하는 시험입니다.
기초 10문제(각 2점), 심화형 2문제(각 5점)으로 편성돼 있습니다. 답안은 #1. #2. #3. 식으로 제목을 붙이고 코드를 아래에 붙여 "학번_이름_중간고사.r"로 저장해서 보내면 됩니다.

## 준비

tidyverse 패키지를 미리 설치해 둡니다.

## 기초 10문제

1. 근의 공식을 r의 수식으로 표시하시오. (예: (a*b-2)/2)
2. "tidytext"라는 패키지를 설치하고 작업할 수 있도록 하는 명령어를 입력하시오.
3. "반갑습니다." "저는" "현아입니다."를 붙여서 화면에 출력하게 하는 명령어를 입력하시오.
4. mtcars라는 데이터셋의 '전체' 기초통계량을 확인할 수 있는 명령어를 입력하시오.
5. mtcars 데이터셋의 처음 5개 행을 확인할 수 있는 명령어를 입력하시오.
6. mtcars 데이터셋의 mpg, disp, drat 열만 추려내는 명령어를 입력하시오.
7. txhousing이라는 데이터셋을 RStudio 우측 상단 Environment에 불러오고 사용할 수 있게 하는 명령어를 입력하시오. 
8. txhousing의 "median" 변수를 120000을 기준으로 해서 "low", "high"로 평가해 "test" 변수를 만드는 명령어를 작성하시오. (한줄로 작성하시오)
9. txhousing의 "volume" 변수를 "size"로 이름을 바꾸는 명령어를 입력하시오.
10. txhousing의 도시별("city") 빈도를 표로 확인하는 명령어를 입력하시오.

## 심화 2문제

###1. economics 데이터를 활용하여 다음 문제를 푸시오
1) 실업률(uempmed) 5% 10% 기준으로 "low", "normal", "high"로 분류해 status 변수로 만드시오 (economics 데이터프레임에 저장)
2) status 변수에서 "low"", "normal"", "high" 별 빈도수를 히스토그램으로 그리시오 (ggplot 활용)
3) status 변수별로 실업자 평균수를 "unemployed_average"로 요약하시오.

###2. Lahman 패키지를 설치 후 패키지를 로드하시오. Batting 데이터 셋을 로드한 후 다음 문제를 푸시오
1) 타석(AB)과 안타(H)을 가지고 타율을 소숫점 3자리로 반올림한 "avg"라는 변수를 만드시오. (예: 0.385) (mutate 명령어로 만들어 볼 것. 결과물을 Batting에 저장)
2) 타점(RBI)이 100개 이상인 타자만 추려서, 내림차순으로 정렬해 상위 10개 기록만 추려내시오.
3) 타자(playerID)별로 누적 타점을 추리고(SUM_RBI), 누적 타점 기준 상위 10 명의 기록만 추려내시오.